#!/bin/sh -e
# This file is part of the Redis k8s Charm for Juju.
# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

if [ -z "$VIRTUAL_ENV" -a -d venv/ ]; then
    . venv/bin/activate
fi

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH="lib:src"
else
    export PYTHONPATH="lib:src:$PYTHONPATH"
fi

flake8
coverage run --source=src -m unittest -v "$@"
coverage report -m
